Repository optuna/optuna-examples, pull requests merged in 2022-06, with the labels that each got.

#121 Drop Python 3.6 support
  .github/workflows/base.yml
  .github/workflows/catboost.yml
  .github/workflows/chainer.yml
  .github/workflows/dask_ml.yml
  .github/workflows/hiplot.yml
  .github/workflows/hydra.yml
  .github/workflows/lightgbm.yml
  .github/workflows/multi_objective.yml
  .github/workflows/mxnet.yml
  .github/workflows/pytorch.yml
  .github/workflows/ray.yml
  .github/workflows/rl.yml
  .github/workflows/samplers.yml
  .github/workflows/skimage.yml
  .github/workflows/sklearn.yml
  .github/workflows/visualization.yml
  .github/workflows/wandb.yml
  .github/workflows/xgboost.yml
Labels: CI

#120 Run `quickstart.ipynb` in `base` task
  .github/workflows/base.yml
  requirements.txt
Labels: CI

#119 Introduce stale bot.
  .github/workflows/stale.yml
Labels: other

#123 Fix CI due to `thop`
  multi_objective/requirements.txt
Labels: installation

#125 Remove unreferrenced variable in pytorch_simple.py
  pytorch/pytorch_simple.py
Labels: code-fix
