Repository optuna/optuna-examples, pull requests merged in 2023-03, with the labels that each got.

#175 Minor code change suggestions to `pytorch_distributed_spawn.py`
  pytorch/pytorch_distributed_spawn.py
Labels: code-fix

#176 Install `optuna-integration` in `chainer` CI
  .github/workflows/chainer.yml
Labels: CI

#177 Add python 3.11 skimage's version matrix and remove warning for inputs data
  .github/workflows/skimage.yml
  skimage/skimage_lbp_simple.py
Labels: enhancement

#174 Add python 3.11 to ray's version matrix
  .github/workflows/ray.yml
Labels: CI, stale

#179 Update pytorch lightning version for ddp
  .github/workflows/pytorch.yml
  pytorch/pytorch_lightning_ddp.py
Labels: code-fix
