Repository optuna/optuna-examples, pull requests merged in 2023-05, with the labels that each got.

#186 Run catboost example with python 3.11
  .github/workflows/catboost.yml
Labels: CI

#183 Install optnua integration on ci.
  .github/workflows/allennlp.yml
  .github/workflows/keras.yml
Labels: stale

#191 Use Gymnasium and pre-released Stable-Baselines3
  .github/workflows/rl.yml
  rl/sb3_simple.py
Labels: bug

#193 Fix the AllenNLP CI
  allennlp/requirements.txt
Labels: CI
