Repository optuna/optuna-examples, pull requests merged in 2025-04, with the labels that each got.

#312 Fix fastai Example
  .github/workflows/fastai.yml
  fastai/fastai_simple.py
Labels: CI

#305 Add Example for Comet
  comet/comet_integration.py
  comet/requirements.txt
Labels: feature

#313 Update PyTorch Checkpoint Example using tempfile
  pytorch/pytorch_checkpoint.py
Labels: enhancement

#315 [hotfix] Fix Dask-ML example by adding the version constraint on numpy
  .github/workflows/dask_ml.yml
Labels: CI

#311 Add workflow dispatch
  .github/workflows/aim.yml
  .github/workflows/allennlp.yml
  .github/workflows/base.yml
  .github/workflows/basic.yml
  .github/workflows/catboost.yml
  .github/workflows/checks.yml
  .github/workflows/dashboard.yml
  .github/workflows/dask.yml
  .github/workflows/dask_ml.yml
  .github/workflows/faq.yml
  .github/workflows/fastai.yml
  .github/workflows/haiku.yml
  .github/workflows/hiplot.yml
  .github/workflows/hydra.yml
  .github/workflows/keras.yml
  .github/workflows/lightgbm.yml
  .github/workflows/mlflow.yml
  .github/workflows/multi_objective.yml
  .github/workflows/openml.yml
  .github/workflows/pruners.yml
  .github/workflows/pytorch.yml
  .github/workflows/rapids.yml
  .github/workflows/ray.yml
  .github/workflows/rl.yml
  .github/workflows/samplers.yml
  .github/workflows/skimage.yml
  .github/workflows/sklearn.yml
  .github/workflows/tensorboard.yml
  .github/workflows/tensorflow.yml
  .github/workflows/terminator.yml
  .github/workflows/tfkeras.yml
  .github/workflows/visualization.yml
  .github/workflows/wandb.yml
  .github/workflows/xgboost.yml
Labels: CI
